<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SarojPulajwar" failures="1" tests="1" name="Test" time="36.989" errors="0" timestamp="2022-12-23T12:59:01 IST">
  <testcase classname="com.TestLayer.LogginTest" name="verifyLoginTest" time="0.048">
    <failure type="java.lang.AssertionError" message="expected [https://suite8demo.suiteondemand.com/#/home] but found [https://suite8demo.suiteondemand.com/#/Login]">
      <![CDATA[java.lang.AssertionError: expected [https://suite8demo.suiteondemand.com/#/home] but found [https://suite8demo.suiteondemand.com/#/Login]
at com.TestLayer.LogginTest.verifyLoginTest(LogginTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginTest -->
</testsuite> <!-- Test -->
